### PR TITLE
Complete but not autogenerated Marketplace

### PR DESCRIPTION
**Pull request by N-Shar-ma**
- Data is read from `appDetails.json` and displayed in Marketplace
- Updated instructions to add new app to marketplace (until the import issue is fixed)

Still left to do:
- [ ] Improve UI (for example, cards are too long right now)

### CODE REVIEW

**Review by hargup — COMMENTED** [review]
LGTM

**Comment by hargup** [comment]
I tested locally, works well 🎉, feel free to merge it.


Screenshot 2021-12-02 at 11 21 27 AM

Suggestions to improve the PR:
- Adding a screenshot of the output helps people judge the result faster :) 

Note about processs:
- (If you merge permissions) The person creating the pull request merges the pull request, so submit the work when you are feel it's ready. 
- Prefer to be baised towards merging the pull request sooner than later. Merged but somewhat unpolished work is more useful than, and highly polished but unmerged work. You can create tickets about all the improvements which needs to be done on top of this work

**Comment by hargup** [comment]
@N-Shar-ma how did you generate `src/components/appDetails.json` ?

**Comment by N-Shar-ma** [comment]
> @N-Shar-ma how did you generate `src/components/appDetails.json` ? 

Through the marketplace instant app itself! Details in the PR: https://github.com/felvin-search/instant-apps/pull/246

**Pull request merged**
